[build]
builder = "nixpacks"

[deploy]
startCommand = "sleep 10 && node dist/src/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 